export const getGenreName = id => {
  const genreName =
    id == "28"
      ? "Action"
      : id == "12"
      ? "Adventure"
      : id == "16"
      ? "Animation"
      : id == "35"
      ? "Comedy"
      : id == "80"
      ? "Crime"
      : id == "99"
      ? "Documentry"
      : id == "18"
      ? "Drama"
      : id == "10751"
      ? "Family"
      : id == "14"
      ? "Fantasy"
      : id == "36"
      ? "History"
      : id == "27"
      ? "Horror"
      : id == "10402"
      ? "Music"
      : id == "9648"
      ? "Mystery"
      : id == "10749"
      ? "Romance"
      : id == "878"
      ? "Science Fiction"
      : id == "10770"
      ? "Tv Movie"
      : id == "53"
      ? "Thriller"
      : id == "10752"
      ? "War"
      : id == "37"
      ? "Westren"
      : null;
  return genreName;
};
