export const UPCOMING_MOVIES_START="UPCOMING_MOVIES_START";
export const UPCOMING_MOVIES_FAILED="UPCOMING_MOVIES_FAILED";
export const UPCOMING_MOVIES_SUCCESS="UPCOMING_MOVIES_SUCCESS";

export const GET_VIDEO_START="GET_VIDEO_START";
export const GET_VIDEO_FAILED="GET_VIDEO_FAILED";
export const GET_VIDEO_SUCCESS="GET_VIDEO_SUCCESS";