export const SEARCH_MOVIES_START = "SEARCH_MOVIES_START";
export const SEARCH_MOVIES_FAILED = "SEARCH_MOVIES_FAILED";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";

export const SEARCH_WORD_MOVIES_START = "SEARCH_WORD_MOVIES_START";
export const SEARCH_WORD_MOVIES_SUCCESS = "SEARCH_WORD_MOVIES_SUCCESS";
export const SEARCH_WORD_MOVIES_FAILED = "SEARCH_WORD_MOVIES_FAILED";
