export const SPECIFIC_MOVIE_START = "SPECIFIC_MOVIE_START";
export const SPECIFIC_MOVIE_FAILED = "SPECIFIC_MOVIE_FAILED";
export const SPECIFIC_MOVIE_SUCCESS = "SPECIFIC_MOVIE_SUCCESS";

export const SIMILAR_MOVIE_START = "SIMILAR_MOVIE_START";
export const SIMILAR_MOVIE_FAILED = "SIMILAR_MOVIE_FAILED";
export const SIMILAR_MOVIE_SUCCESS = "SIMILAR_MOVIE_SUCCESS";
